import Head from 'next/head'
import Image from 'next/image'
import MainLayout from '../components/common/MainLayout/MainLayout'
import styles from '../styles/Home.module.css'

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>home page</title>
      </Head>
      <MainLayout>
        <div className={styles.homeContainer}>
          <h1 className={styles.heading}>history of our company</h1>
          <p className={styles.paragraph}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet vulputate mi. Duis facilisis nunc sed turpis elementum, vitae dapibus felis congue. Nullam in luctus nisl. Nullam sodales sagittis dolor, vel iaculis massa eleifend lobortis. Suspendisse aliquam dictum nisl, non varius odio mollis vel. Donec consectetur in est ac interdum. Etiam pretium lacinia diam, in interdum lectus rutrum non. Morbi id turpis ut dolor interdum mattis. Mauris sit amet sem blandit, consequat augue id, malesuada tortor. Praesent porta ipsum quis feugiat ultrices. Maecenas nec ornare quam. Fusce facilisis tellus felis, et venenatis erat euismod eu. Maecenas at semper dui. Mauris rutrum venenatis mollis. Aenean scelerisque convallis mollis. Cras malesuada, eros at congue egestas, neque mauris convallis libero, non maximus metus lorem sed neque.

Curabitur facilisis mauris ligula, quis pharetra diam bibendum a. Quisque id tempus urna. Pellentesque non urna tempus, maximus lacus vel, ultrices ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque viverra fermentum rutrum. Phasellus vitae suscipit nunc, at maximus mauris. Integer vehicula sapien ac posuere convallis. Suspendisse sit amet suscipit dolor, ut luctus neque. Sed varius orci in ex interdum, vel efficitur ipsum lacinia. Praesent eget nunc ante. Mauris tortor elit, tincidunt ac fringilla sed, hendrerit id augue. Vivamus fringilla sollicitudin iaculis. Donec et dolor ut ante auctor molestie a ut nibh. Sed id augue libero.

Suspendisse non iaculis dolor. Fusce volutpat dictum auctor. Sed at ligula ac dolor faucibus porta. Fusce fermentum, neque id vestibulum fermentum, purus arcu rutrum ipsum, id dictum velit purus ut mauris. Morbi eget ligula quis odio efficitur euismod in et ante. Quisque bibendum euismod erat, et vulputate sem. Vivamus suscipit venenatis velit ac pulvinar. In vitae ultrices mi. Quisque eu mi tincidunt, dignissim mi a, tincidunt ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean leo lacus, aliquet nec aliquet nec, congue sed eros. Aenean sodales ex at lectus mattis malesuada.

In semper faucibus ipsum a iaculis. Morbi sit amet ornare odio. Nullam quam nibh, vestibulum quis dictum ac, porttitor quis erat. Vestibulum metus diam, imperdiet id sem eu, aliquet aliquam eros. Vivamus viverra turpis eu metus luctus facilisis. Cras vitae est hendrerit leo efficitur fermentum venenatis in massa. Nunc orci magna, blandit tempus dapibus sed, sollicitudin id dolor. Nullam quis vulputate leo.

Suspendisse cursus, risus et mollis tristique, lacus elit gravida elit, eget elementum nibh purus sit amet turpis. Nunc ac nisl justo. Phasellus quis porta neque. Curabitur id venenatis eros. Donec quis felis id turpis laoreet sodales viverra at lorem. Donec tempus ante sem, sed ultricies justo placerat et. Curabitur tempor magna non dui sagittis, sed auctor arcu euismod. Suspendisse venenatis nunc eget est tincidunt dictum. Aliquam nec nisi eu metus convallis pulvinar eu eget massa. Sed at ligula turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin volutpat dui id metus porta, ut dictum est tincidunt. Duis lacus purus, facilisis at ante sit amet, accumsan efficitur turpis. Maecenas ullamcorper lacus eget dui mattis elementum.

Pellentesque id eros mauris. Ut massa sem, luctus eget mi nec, tempor faucibus eros. Suspendisse potenti. Duis ante erat, pharetra et metus non, dictum molestie tortor. Curabitur mauris magna, blandit lacinia vestibulum accumsan, feugiat eu massa. Nullam vel condimentum erat. Nam sit amet lacinia turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean fringilla risus nulla, sit amet sollicitudin mi feugiat posuere. Cras tincidunt tortor et arcu tincidunt aliquet. Praesent mattis ipsum blandit hendrerit volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Duis volutpat turpis at risus ornare, ut semper mauris tincidunt. Sed sed est ac sem accumsan tristique non sed odio. Mauris rutrum dui arcu, vel hendrerit purus mattis eget. Mauris elit tellus, dignissim in nisl nec, rutrum interdum magna. Donec sollicitudin id libero eu tristique. Praesent nec volutpat tortor. Phasellus congue libero non lectus consequat posuere. In ut diam id felis venenatis tincidunt a id mauris. Praesent vitae tortor hendrerit, elementum mi id, semper lorem. Aliquam ut porttitor nibh. Mauris volutpat condimentum consequat. Morbi elementum rutrum dui, quis posuere est convallis nec. Donec rutrum placerat tortor vel varius. Nullam ac rutrum ipsum, ut elementum odio.

Morbi non felis turpis. Maecenas semper dolor vitae urna fermentum consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras et porta nisl, nec tincidunt lorem. Phasellus commodo sapien dolor, nec lacinia turpis cursus sed. Aliquam augue felis, laoreet nec sollicitudin vel, maximus in velit. Fusce accumsan tristique nisl. Morbi viverra ex sed ullamcorper mattis. Maecenas vitae risus dictum, ultricies ligula id, sollicitudin neque. Quisque dui enim, feugiat vitae nunc sed, fermentum dictum mauris.

Vestibulum lobortis elit vel ultrices gravida. Integer eu felis ut ante rutrum lobortis. Nunc nec pellentesque quam. Proin tincidunt velit gravida sem laoreet, in cursus est vehicula. Cras quis faucibus erat. Phasellus mollis ullamcorper turpis, vel gravida quam dapibus facilisis. Nulla dictum purus eget nisi facilisis condimentum ut non nulla. Mauris eu magna magna. Praesent at pellentesque ante. Ut varius tellus vitae orci aliquam, nec scelerisque ipsum tempor. Nam mattis dolor sed gravida rutrum. Nam ac maximus ex, sed pharetra ipsum. Phasellus iaculis rutrum sem at mattis.

Aliquam eget dictum urna, quis mattis arcu. Ut laoreet, nibh ullamcorper blandit sodales, velit sem blandit libero, vel cursus turpis felis nec tortor. Nam metus libero, scelerisque a tempus non, aliquet ac magna. Mauris porttitor a lorem eget pharetra. Ut et ullamcorper metus. Sed vitae erat tincidunt, interdum odio at, facilisis erat. Suspendisse mollis lectus augue, eleifend vulputate sapien egestas eget. Sed eleifend augue non sem vestibulum luctus.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet vulputate mi. Duis facilisis nunc sed turpis elementum, vitae dapibus felis congue. Nullam in luctus nisl. Nullam sodales sagittis dolor, vel iaculis massa eleifend lobortis. Suspendisse aliquam dictum nisl, non varius odio mollis vel. Donec consectetur in est ac interdum. Etiam pretium lacinia diam, in interdum lectus rutrum non. Morbi id turpis ut dolor interdum mattis. Mauris sit amet sem blandit, consequat augue id, malesuada tortor. Praesent porta ipsum quis feugiat ultrices. Maecenas nec ornare quam. Fusce facilisis tellus felis, et venenatis erat euismod eu. Maecenas at semper dui. Mauris rutrum venenatis mollis. Aenean scelerisque convallis mollis. Cras malesuada, eros at congue egestas, neque mauris convallis libero, non maximus metus lorem sed neque.

Curabitur facilisis mauris ligula, quis pharetra diam bibendum a. Quisque id tempus urna. Pellentesque non urna tempus, maximus lacus vel, ultrices ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque viverra fermentum rutrum. Phasellus vitae suscipit nunc, at maximus mauris. Integer vehicula sapien ac posuere convallis. Suspendisse sit amet suscipit dolor, ut luctus neque. Sed varius orci in ex interdum, vel efficitur ipsum lacinia. Praesent eget nunc ante. Mauris tortor elit, tincidunt ac fringilla sed, hendrerit id augue. Vivamus fringilla sollicitudin iaculis. Donec et dolor ut ante auctor molestie a ut nibh. Sed id augue libero.

Suspendisse non iaculis dolor. Fusce volutpat dictum auctor. Sed at ligula ac dolor faucibus porta. Fusce fermentum, neque id vestibulum fermentum, purus arcu rutrum ipsum, id dictum velit purus ut mauris. Morbi eget ligula quis odio efficitur euismod in et ante. Quisque bibendum euismod erat, et vulputate sem. Vivamus suscipit venenatis velit ac pulvinar. In vitae ultrices mi. Quisque eu mi tincidunt, dignissim mi a, tincidunt ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean leo lacus, aliquet nec aliquet nec, congue sed eros. Aenean sodales ex at lectus mattis malesuada.

In semper faucibus ipsum a iaculis. Morbi sit amet ornare odio. Nullam quam nibh, vestibulum quis dictum ac, porttitor quis erat. Vestibulum metus diam, imperdiet id sem eu, aliquet aliquam eros. Vivamus viverra turpis eu metus luctus facilisis. Cras vitae est hendrerit leo efficitur fermentum venenatis in massa. Nunc orci magna, blandit tempus dapibus sed, sollicitudin id dolor. Nullam quis vulputate leo.

Suspendisse cursus, risus et mollis tristique, lacus elit gravida elit, eget elementum nibh purus sit amet turpis. Nunc ac nisl justo. Phasellus quis porta neque. Curabitur id venenatis eros. Donec quis felis id turpis laoreet sodales viverra at lorem. Donec tempus ante sem, sed ultricies justo placerat et. Curabitur tempor magna non dui sagittis, sed auctor arcu euismod. Suspendisse venenatis nunc eget est tincidunt dictum. Aliquam nec nisi eu metus convallis pulvinar eu eget massa. Sed at ligula turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin volutpat dui id metus porta, ut dictum est tincidunt. Duis lacus purus, facilisis at ante sit amet, accumsan efficitur turpis. Maecenas ullamcorper lacus eget dui mattis elementum.

Pellentesque id eros mauris. Ut massa sem, luctus eget mi nec, tempor faucibus eros. Suspendisse potenti. Duis ante erat, pharetra et metus non, dictum molestie tortor. Curabitur mauris magna, blandit lacinia vestibulum accumsan, feugiat eu massa. Nullam vel condimentum erat. Nam sit amet lacinia turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean fringilla risus nulla, sit amet sollicitudin mi feugiat posuere. Cras tincidunt tortor et arcu tincidunt aliquet. Praesent mattis ipsum blandit hendrerit volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Duis volutpat turpis at risus ornare, ut semper mauris tincidunt. Sed sed est ac sem accumsan tristique non sed odio. Mauris rutrum dui arcu, vel hendrerit purus mattis eget. Mauris elit tellus, dignissim in nisl nec, rutrum interdum magna. Donec sollicitudin id libero eu tristique. Praesent nec volutpat tortor. Phasellus congue libero non lectus consequat posuere. In ut diam id felis venenatis tincidunt a id mauris. Praesent vitae tortor hendrerit, elementum mi id, semper lorem. Aliquam ut porttitor nibh. Mauris volutpat condimentum consequat. Morbi elementum rutrum dui, quis posuere est convallis nec. Donec rutrum placerat tortor vel varius. Nullam ac rutrum ipsum, ut elementum odio.

Morbi non felis turpis. Maecenas semper dolor vitae urna fermentum consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras et porta nisl, nec tincidunt lorem. Phasellus commodo sapien dolor, nec lacinia turpis cursus sed. Aliquam augue felis, laoreet nec sollicitudin vel, maximus in velit. Fusce accumsan tristique nisl. Morbi viverra ex sed ullamcorper mattis. Maecenas vitae risus dictum, ultricies ligula id, sollicitudin neque. Quisque dui enim, feugiat vitae nunc sed, fermentum dictum mauris.

Vestibulum lobortis elit vel ultrices gravida. Integer eu felis ut ante rutrum lobortis. Nunc nec pellentesque quam. Proin tincidunt velit gravida sem laoreet, in cursus est vehicula. Cras quis faucibus erat. Phasellus mollis ullamcorper turpis, vel gravida quam dapibus facilisis. Nulla dictum purus eget nisi facilisis condimentum ut non nulla. Mauris eu magna magna. Praesent at pellentesque ante. Ut varius tellus vitae orci aliquam, nec scelerisque ipsum tempor. Nam mattis dolor sed gravida rutrum. Nam ac maximus ex, sed pharetra ipsum. Phasellus iaculis rutrum sem at mattis.

Aliquam eget dictum urna, quis mattis arcu. Ut laoreet, nibh ullamcorper blandit sodales, velit sem blandit libero, vel cursus turpis felis nec tortor. Nam metus libero, scelerisque a tempus non, aliquet ac magna. Mauris porttitor a lorem eget pharetra. Ut et ullamcorper metus. Sed vitae erat tincidunt, interdum odio at, facilisis erat. Suspendisse mollis lectus augue, eleifend vulputate sapien egestas eget. Sed eleifend augue non sem vestibulum luctus.
</p>
</div>
          </MainLayout>
    </div>
  )
}

